Diagnostics:
  ClangTidy:
    Add:
      - bugprone-*
      - concurrency-*
      - cppcoreguidelines-*
      - google-*
      # - modernize-*
      - performance-*
      - portability-*
      - readability-*
    Remove:
      - modernize-use-trailing-return-type
    CheckOptions:
      readability-identifier-naming.VariableCase: camelBack
      cppcoreguidelines-macro-usage.CheckCapsOnly: true
InlayHints:
  Enabled: Yes
  ParameterNames: No
  DeducedTypes: Yes
